services:
  web:
    build: .
    container_name: Codify_Project
    volumes:
      - ./www:/var/www/html
    restart: always
    depends_on:
      - database
    ports:
      - "8000:80"

  database:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: 'codify_database'
      volumes:
        - "data-pdo:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  data-pdo: